### ISSUE TITLE
Decimal вместо float

### ISSUE THREAD

**Issue by ttyS15** [yandex-money/yandex-checkout-sdk-python#11]
Привет! 

А по какой причине для хранения количества денег использует float? 

В общем случае это не корректно из-за округлений чисел с плавающей запятой. Можем предложить изменения с заменой на Decimal.

https://github.com/yandex-money/yandex-checkout-sdk-python/blob/cb950e722b0c8334165369ccdf188118e0366b75/yandex_checkout/domain/models/amount.py#L18

**Comment by ostulov** [comment]
Мы планируем отказаться от float, однако это потребует некоторого времени.

**Comment by ostulov** [comment]
Задачу про номера карт взяли в работу.  Про срок решения напишу чуть позже.

**Comment by Olegt0rr** [comment]
Посмотрите аналогичные библиотеки банков. Там везде самая простая и прозрачная реализация - работа с минимальной величиной (центы, копейки).

float для работы с финансами - это мощный факап
А глядя на срок реализации так и хочется разнообразить посты про Яндекс на хабре

**Comment by ostulov** [comment]
Добрый день!

В настоящий момент мы работаем над добавлением новых возможностей в sdk. В будущем мы планируем исправить использование float в данном случае.

**Comment by ostulov** [comment]
Было исправлено в v1.6.0
