### ISSUE TITLE
Номера карт короче 16 символов

### ISSUE THREAD

**Issue by pycott** [yandex-money/yandex-checkout-sdk-python#22]
Хотя в последней версии была заявлена поддержка типа карт "Diners Club", однако оплата картами с номерами короче 16 символов все равно не проходит. Так, например, тестовая yandex карта  Diners Club имеет номер 36700102000000 (14 символов) и на [строке проверки формата](https://github.com/yandex-money/yandex-checkout-sdk-python/blob/master/yandex_checkout/domain/models/payment_data/request/credit_card.py#L24) отваливается.

Согласно [вики по номерам карт](https://en.wikipedia.org/wiki/Payment_card_number), номера карт могут начинаться с 12 символов.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, добавим в SDK поддержку таких карт.

**Comment by ostulov** [comment]
Исправлено выложено в версии v1.0.12
