### ISSUE TITLE
 Не поддерживаются номера телефонов с '+'.

### ISSUE THREAD

**Issue by porkhun** [yandex-money/yandex-checkout-sdk-python#23]
При указании номера телефона '+7925*******' в рецепте получаю Invalid phone value type.
Регулярка в yandex_checkout/domain/models/receipt.py:65 не поддерживает '+' в начале строки, хотя стандарт ITU-T E.164, на который ссылается ваша документация, допускает указание номера телефона через '+'.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание, проверим.

**Comment by ostulov** [comment]
Указание номера телефона через знак + не поддерживается в Яндекс.Кассе.
Под соответствием стандарту ITU-T E.164 подразумевается структура формирования телефонного номера.
