### ISSUE TITLE
Не работает пример создания Умного платежа из раздела "Быстрый старт"

### ISSUE THREAD

**Issue by dharmagetic** [yandex-money/yandex-checkout-sdk-python#30]
В разделе "Быстрый старт" https://kassa.yandex.ru/developers/payments/quick-start не работает пример создания Умного платежа (пробовал с идентификаторами и секретными ключами тестового и реального магазинов):

`from yandex_checkout import Configuration, Payment

Configuration.account_id = <Идентификатор магазина>
Configuration.secret_key = <Секретный ключ>

payment = Payment.create({
    "amount": {
        "value": "100.00",
        "currency": "RUB"
    },
    "confirmation": {
        "type": "redirect",
        "return_url": "https://www.merchant-website.com/return_url"
    },
    "capture": true,
    "description": "Заказ №1"
})` 

Получаю ошибку:
`    215                 self.__set_validation_error('Both payment_method_id and payment_data values are specified')
    216 
--> 217         if self.payment_method_data.type == PaymentMethodType.BANK_CARD \
    218                 and self.payment_method_data.card is not None:
    219             # Get current date with an offset.

AttributeError: 'NoneType' object has no attribute 'type'`

**Comment by dharmagetic** [comment]
Версия библиотеки 1.1.0
Вызов Curl с параметрами из примера создания Умного платежа отрабатывает без проблем

**Comment by ozeranskiy** [comment]
Проблема связана с тем, что в последнем обновлении проверяется необязательный при создании платежа парамтер payment_method_data, из документации:

> Данные для оплаты конкретным способом (payment_method). Вы можете не передавать этот объект в запросе. В этом случае пользователь будет выбирать способ оплаты на стороне Яндекс.Кассы.

в PR https://github.com/yandex-money/yandex-checkout-sdk-python/pull/31 я исправил эту ситуацию. Если payment_method_data не передан, то проверка https://github.com/yandex-money/yandex-checkout-sdk-python/blob/master/yandex_checkout/domain/request/payment_request.py#L217 осуществляться не будет.

**Comment by dharmagetic** [comment]
@ozeranskiy спасибо!
до понедельника получится обновить версию библиотеки на Pypi ?)

**Comment by ostulov** [comment]
Добрый день!

Мы рассмотрим добавление pull request. По сроку обновления пока сказать не могу.

**Comment by ozeranskiy** [comment]
> Добрый день!
> 
> Мы рассмотрим добавление pull request. По сроку обновления пока сказать не могу.

думаю, что многие могли столкнуться с проблемой создания платежей после перехода на версию 1.1.0. Вы можете выпустить патч версию с моим PR в ближайшее время?

**Comment by dharmagetic** [comment]
@ostulov 
Добрый день !
Подскажите пожалуйста, когда будет исправлена эта проблема ?

**Comment by ostulov** [comment]
@dharmagetic 
Добрый день!

Пока точный срок назвать не могу.

**Comment by ostulov** [comment]
Было исправлено в версии v1.1.1
