### ISSUE TITLE
Issues when installing 1.4 version

### ISSUE THREAD

**Issue by ComradeLV** [yandex-money/yandex-checkout-sdk-python#42]
`Collecting yandex_checkout
  Downloading https://files.pythonhosted.org/packages/7d/5c/10414c1260fc35e46e71e034bea3b516f4971910248989e55b12880dd838/yandex_checkout-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zcw8ebou/yandex-checkout/setup.py", line 8, in <module>
        with open("README.en.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.en.md'
    
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zcw8ebou/yandex-checkout/`

1.3.1 installs successfully

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, выложили исправление.
