### ISSUE TITLE
Invalid customer value type

### ISSUE THREAD

**Issue by RevengeJuice** [yandex-money/yandex-checkout-sdk-python#44]
Должно быть elif вместо if.
Иначе, когда value это dict, всегда будет TypeError
https://github.com/yandex-money/yandex-checkout-sdk-python/blob/20b1fa4974db9e1661a6787bd5bb92ca13dfadf2/yandex_checkout/domain/models/receipt.py#L26

**Comment by ostulov** [comment]
Исправили в v1.4.6
