### ISSUE TITLE
JSON Serializable Please

### ISSUE THREAD

**Issue by ismailbayram** [yandex-money/yandex-checkout-sdk-python#52]
I would like to serialize all fields in Response to JSON.
for example:
`json.loads(response)` or `response.json()`

**Comment by ilyandex** [comment]
Thank you for your advice. We will consider this issue in future releases.

**Comment by kostya-ten** [comment]
Да действительно нужно отдать мобилке JSON ответа, после платежного токена.

**Comment by ostulov** [comment]
Fixed.
