### ISSUE TITLE
Добавить поля issuer_country и issuer_name в класс CreditCard

### ISSUE THREAD

**Issue by emorozov** [yandex-money/yandex-checkout-sdk-python#55]
Данные поля возвращаются в уведомлениях и описаны в документации:
https://kassa.yandex.ru/developers/using-api/webhooks

Но лезть за ними приходится напрямую в запрос, так как в `CreditCard` определены только поля `first6`, `last4`, `expiry_year`, `expiry_month` и `card_type`.

Нельзя ли добавить также данные поля, чтобы можно было упростить код, обрабатывающий уведомления, пожалуйста.

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение. Подумаем над внесением такого изменения.

**Comment by ostulov** [comment]
Выполнено.
